CREATE DATABASE hugocieri;

USE hugocieri;

CREATE TABLE categories (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);

DESCRIBE categories;

INSERT INTO categories VALUES
(1, "construccion"),
(2, "baño y cocina"),
(3, "pisos y pinturas"),
(4, "terminaciones"),
(5, "decoracion"),
(6, "aire libre y jardin"),
(7, "electrohogar")

INSERT INTO sub_category VALUES
(1, "Fuentes", 6),
(2, "Budas", 6),
(3, "Sillas y mesas", 6),
(4, "Piletas", 6),
(5, "Mangrullos", 6),
(6, "Hamacas", 6),
(6, "Palmeras y Plantas", 6),


SELECT * FROM categories;

CREATE TABLE products (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    image TEXT NOT NULL,
    price INT(11) NOT NULL,
    description TEXT,
    category_id INT(11) NOT NULL,
    PRIMARY KEY (id)
)

INSERT INTO products VALUES
(1, "Plasticor", "https://laeconomica.com.ar/wp-content/uploads/2021/07/plasticor-cemento-de-albanileria-por-pallet-D_NQ_NP_397011-MLA20450790485_102015-F.jpg", 1200, "Plasticor de 25k", 1),
(2, "Cemento", "https://http2.mlstatic.com/D_NQ_NP_735240-MLA47692266576_092021-O.jpg", 1600, "Bolsa de cemento x 50kg", 1),
(3, "Cal", "https://arcencohogar.vtexassets.com/arquivos/ids/300247/1994308-1.jpg", 700, "Este producto es el resultado de investigaciones y desarrollos realizados en los laboratorios de Cementos Avellaneda S. A.", 1),
(4, "Cal viva", "https://castienda.com.ar/wp-content/uploads/2020/06/cal_viva_andina-508x508.jpg", 1170, "Se utiliza en la producción de morteros, yesos, cementos etc. Previamente hidratada.", 1),
(5, "Bolson de arena", "https://images.obi.de/product/DE/1500x1500/416583_2.jpg", 5719, "Bolson con arena fina", 1),
(6, "Bolsa de arena", "https://serymat.com/wp-content/uploads/2020/11/arena-bolsa-1.jpg", 400, "Bolsa con arena fina", 1),
(7, "Inodoro", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2467054?fmt=jpg", 74999, "Indoro", 2),
(8, "Bidet", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2129205?fmt=jpg", 29199, "Bidet", 2),
(9, "Deposito inodoro", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2149923?fmt=jpg", 68199, "Deposito para inodoro", 2),
(10, "Lavamanos", "https://sodimacar.scene7.com/is/image/SodimacArgentina/1118269?fmt=jpg", 8199, "Lavamanos", 2),
(11, "Griferia", "https://sodimacar.scene7.com/is/image/SodimacArgentina/1702580?fmt=jpg", 59399, "Griferia para baños", 2),
(12, "Barra para ducha", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2409720?fmt=jpg", 56999, "Barra para ducha", 2),
(13, "Cerámica Limbo de piso y pared", "https://sodimacar.scene7.com/is/image/SodimacArgentina/3229947?fmt=jpg", 1699, "36 x 36 cm gris", 3),
(14, "Cerámica de interior Ceibo beige", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2630621?fmt=jpg", 1659, "36 x 36 cm Ceibo beige", 3),
(15, "Cerámica de interior Bologna gris", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2441853?fmt=jpg", 1299, "50 x 50 cm", 3),
(16, "Pintura látex", "https://sodimacar.scene7.com/is/image/SodimacArgentina/3236811?fmt=jpg", 3599, "Pintura látex de interior y exterior gris polonia mate lavable 4 L", 3),
(17, "Pintura látex", "https://sodimacar.scene7.com/is/image/SodimacArgentina/1570706?fmt=jpg", 3299, "Pintura látex de interior blanco mate antimoho 20 L", 3),
(18, "Cerámica de exterior Rutilo beige", "https://sodimacar.scene7.com/is/image/SodimacArgentina/2592983?fmt=jpg", 1419, "Cerámica de exterior", 3),

CREATE TABLE orders (
    id INT NOT NULL AUTO_INCREMENT,
    buyer_id INT NOT NULL,
    buyer_name VARCHAR(45) NOT NULL,
    buyer_city TEXT,
    buyer_telephone TEXT,
    product_id INT NOT NULL,
    product_name INT NOT NULL,
    product_price INT(11) NOT NULL,
    product_category_id INT(11) NOT NULL,
)

CREATE TABLE users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    city TEXT,
    telephone TEXT,
    PRIMARY KEY (id)
);

INSERT INTO products VALUES
(19, "Gazebo de polietileno blanco", "https://media.bricocenter.it/v7/https://prodotti.bricocenter.it/media/catalog/product/cache/d04f4ab9ed5e320b97484db27ca6fb65/5/6/561993_08a4.jpg", 15999, "Gazebo de polietileno blanco", 6),
(20, "Juego Jardin 5 Piezas Fundicion Aluminio", "https://http2.mlstatic.com/D_NQ_NP_997351-MLA49395971842_032022-W.jpg", 128199, "Juego Jardin 5 Piezas Fundicion Aluminio", 6),
(21, "Juego chato rectangular (Mesa + 10 sillones)", "https://d3ugyf2ht6aenh.cloudfront.net/stores/531/821/products/27-eaa62b806f7fb5eff116299248114487-480-0.png", 286399, "Juego chato rectangular (Mesa + 10 sillones)", 6),
(22, "Banco chato doble", "https://d3ugyf2ht6aenh.cloudfront.net/stores/531/821/products/file3-11-4a7dec703b17364ee815681347049731-480-0.jpeg", 38999, "Banco chato doble", 6),
(23, "Banco De Madera Tipo Plaza Rústico 1,60cm", "https://http2.mlstatic.com/D_NQ_NP_945808-MLA44510210372_012021-O.jpg", 12399, "Banco De Madera Tipo Plaza Rústico 1,60cm", 6),
(24, "Mesa Rustica Quincho Eucalitpus + 8 Bancos", "https://http2.mlstatic.com/D_NQ_NP_703480-MLA49560304513_042022-W.jpg", 120999, "Mesa Rustica Quincho Eucalitpus + 8 Bancos", 6),
(25, "Hamaca de madera", "https://static.misionesonline.news/wp-content/uploads/2018/09/hamacademadera-7n2f108j9su0.jpg", 82999, "Hamaca de madera", 6),

INSERT INTO products VALUES
(26, "Guardacanto Arco De Aluminio", "https://familiabercomat.quickresults.co/product/image/medium/148494_0.jpg", 2600, "Guardacanto Arco De Aluminio Natural Atrim 8 X 12 Cm 2,5 Mm", 4, 15, "no", "no"),
(27, "Listello Cuadrado Aluminio", "https://accesaniga.com.ar/wp-content/uploads/91601021CROM.jpg", 2450, "Listello Cuadrado Aluminio 20mm 1481 Atrim", 4, 15, "no", "no"),
(28, "Protector de escalón", "https://arcencohogar.vtexassets.com/arquivos/ids/322987/1088568-1.jpg?v=637883220423030000", 5600, "Protector De Escalón Atrim Aluminio Cromo Mate 10.5x20 Mm x2 Mts", 4, 15, "no", "no"),
(29, "Tapacanto esquinero", "https://www.todogriferia.com/product/image/medium/147586_0.jpg", 1000, "TAPACANTO ESQUINERO DE ALUMINIO NATURAL ATRIM 16 X 16 CM 2,5 MM", 4, 15, "no", "no"),
(30, "Zócalo Eps", "https://www.ropelato.com.ar/5080-large_default/zocalo-eps-extra-line-blanco-100mm-x-250m.jpg", 3720, "Zócalo Eps extra line blanco 100mm x 2.50m", 4, 15, "no", "no"),

INSERT INTO products VALUES
(31, "Pegamento Perfecto Placas", "https://perfecto.com.ar/images/producto-placas.jpg", 1600, "Mezcla adhesiva, de base cementícea, apta para aplicaciones “especiales”, de baja absorción de agua, para la colocación de todo tipo de revestimientos cerámicos y pétreos sobre placas de yeso.", 1),
(32, "Pegamento Perfecto Impermeable", "https://perfecto.com.ar/images/producto-impermeable.jpg", 1600, "Es una mezcla adhesiva cementícea para la colocación de revestimientos cerámicos, calcáreos, graníticos y pétreos, de mediana y alta absorción, en interiores y exteriores. Es un adhesivo de baja absorción de agua (I) y de fraguado rápido (F), elaborada a base de Cemento Pórtland de muy alta resistencia, arenas seleccionadas y aditivos de última generación.", 1),
(33, "Pegamento Perfecto Porcellanato", "https://perfecto.com.ar/images/producto-porcellanato.jpg", 1600, "Mezcla adhesiva cementícea de baja absorción de agua, fraguado rápido y resistente al congelamiento y deshielo, para la colocación de todo tipo de revestimientos (baja, media y alta absorción), en interiores y exteriores, de grandes dimensiones, como los porcellanatos y otros materiales pétreos. Elaborada a base de Cemento Pórtland de muy alta resistencia, arenas seleccionadas, aditivos de última generación y polímeros.", 1),
(34, "Pegamento Perfecto Flexible", "https://perfecto.com.ar/images/producto-flexible.jpg", 1600, "Mezcla adhesiva cementícea, de baja absorción de agua y resistente al congelamiento y deshielo, para la colocación de todo tipo de revestimientos cerámicos, porcellantos y materiales pétreos, tanto en interiores como en exteriores. Elaborada a base de cemento portland de muy alta resistencia, arenas seleccionadas, aditivos de última generación y polímeros. Diseñado para colocaciones en condiciones ambientales rigurosas.", 1),
(35, "weber basic ceramicas", "https://www.ar.weber/files/ar/styles/768x768_resize/public/pictures/2018-05/pack-weber-basicceramicas-30kg_2E1CDF7C1A274DFDBDD96E4AD87943C2.jpg", 1600, "Pegamento impermeable para colocar cerámicos en pisos y paredes interiores.", 1),
(36, "weber gris ceramicas", "https://www.ar.weber/files/ar/styles/768x768_resize/public/pictures/2018-05/pack-weber-grisceramicas-30kg_474B89BAE0974DDFA6BB2F6DBE78C24B.jpg", 1600, "Pegamento impermeable para colocar cerámicos en pisos y paredes interiores.", 1),
(37, "weber mix I", "https://www.ar.weber/files/ar/styles/768x768_resize/public/pictures/2018-05/pack-weber-mixI-30kg_366932105EBA4EFEAC13BDE1AF9E1FB6.jpg", 1600, "Mortero 2 en 1 para la realización de revoques interiores.", 1),
(38, "weber mix E", "https://www.ar.weber/files/ar/styles/768x768_resize/public/pictures/2018-05/pack-weber-mixE-30kg_22FF3B9FF7C94522AF6741B3B6809924.jpg", 1600, "Mortero 3 en 1 con ceresita de aplicación manual, para la realización de revoques exteriores.", 1),
(39, "weber fino interior", "https://www.ar.weber/files/ar/styles/768x768_resize/public/pictures/2018-06/pack-weber-fino-25kg.jpg", 1600, "Revoque fino a la cal para interiores, para realizar sobre él todo tipo de terminaciones.", 1),
(40, "Adhesivo impermeable", "https://i1.wp.com/premecol.com.ar/wp-content/uploads/2019/12/impermeable.png", 1600, "Mezcla adhesiva PREMECOL IMPERMEABLE para la colocación en interiores y exteriores de pisos y revestimientos cerámicos normales de alta y media absorción sobre soportes convencionales y hormigón.
Formulada a base de cemento, arenas seleccionadas y aditivos mejoradores de la trabajabilidad, retención de agua y adherencia.", 1),
(41, "Adhesivo porcellanato", "https://i1.wp.com/premecol.com.ar/wp-content/uploads/2019/12/porcellanato.png", 1600, "Mezcla adhesiva PREMECOL PORCELLANATO para la colocación de mármol, piedra natural y en especial porcellanatos normales de baja, media y alta absorción en pisos interiores o exteriores y revestimientos interiores sobre soportes convencionales, hormigón, placas de yeso y cerámica existente.
Está formulada a base de ligantes mixtos (cemento y polímeros redispersables), arenas seleccionadas y aditivos mejoradores de la trabajabilidad, retención de agua y adherencia.", 1),
(42, "Adhesivo refractario", "https://i2.wp.com/premecol.com.ar/wp-content/uploads/2019/12/refractario.png", 1600, "Mezcla adhesiva PREMECOL REFRACTARIO para la colocación de ladrillos refractarios sobre soportes tradicionales y hormigón. Especialmente recomendado para resistir altas temperaturas. Ideal para asadores, chimeneas, hornos y parrillas.
Está formulada a base de cementos especiales, arenas y cargas seleccionadas y aditivos mejoradores de la trabajabilidad, retención de agua y adherencia.", 1),
(43, "Revoque fino interior", "https://i0.wp.com/premecol.com.ar/wp-content/uploads/2019/12/revoque-fino-interior.png", 1600, "El REVOQUE FINO PREMECOL INTERIOR es un producto listo para usar en forma manual en terminaciones de muros y cielorrasos interiores sobre soportes de revoques gruesos convencionales logrando una superficie lista para ser pintada. Es pre dosificado industrialmente a base de cal – cemento, áridos de granulometría seleccionada y aditivos mejoradores de la trabajabilidad, adherencia y resistencia.", 1),
(44, "Revoque fino exterior", "https://i0.wp.com/premecol.com.ar/wp-content/uploads/2019/12/revoque-fino-exterior.png", 1600, "El REVOQUE FINO PREMECOL EXTERIOR es un producto listo para usar en forma manual en terminaciones de muros exteriores, frentes y medianeras sobre revoques gruesos convencionales logrando una superficie lista para ser pintada. Es pre dosificado industrialmente a base de cal – cemento, áridos de granulometría seleccionada, hidrofugantes y aditivos mejoradores de la trabajabilidad, adherencia y resistencia.", 1),

INSERT INTO products VALUES
(45, "Fuente", "https://instagram.faep8-3.fna.fbcdn.net/v/t51.2885-15/272724629_1358782117876256_4157054695097205489_n.jpg", 2600, "", 4, 1, "no", "no", 1),
(46, "", "", 2600, "", 4, 1, "no", "no", 1),
(47, "", "", 2600, "", 4, 1, "no", "no", 1),
(48, "", "", 2600, "", 4, 1, "no", "no", 1),
(49, "", "", 2600, "", 4, 1, "no", "no", 1),
(50, "", "", 2600, "", 4, 1, "no", "no", 1),
(51, "", "", 2600, "", 4, 1, "no", "no", 1),
(52, "", "", 2600, "", 4, 1, "no", "no", 1),

INSERT INTO products VALUES
(88, "Caja ceramica macetera vintage (1,75 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668344863/hcmaterialessrc/ceramicas/bf8a4-macerata_oj30ce.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-20x62,color-vintage", 15),
(89, "Caja ceramica alessandria (1,75 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668345605/hcmaterialessrc/ceramicas/e28ba-alessandria-web_jsju1r.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-20x62,color-gris_claro", 15),
(90, "Caja ceramica udine (1,75m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348366/hcmaterialessrc/ceramicas/8fa1f-udine-web_ru87to.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-20x62,color-arena", 15),
(91, "Caja ceramica vicenza (1,75 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348405/hcmaterialessrc/ceramicas/96308-vicensa-web_i6xyfm.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-20x62,color-gris_oscuro", 15),
(92, "Caja ceramica monza (1,75 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348424/hcmaterialessrc/ceramicas/8b3ea-moza-web_bvwdsx.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-20x62,color-destonolizado", 15),
(93, "Caja ceramica veneto (1,75 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348446/hcmaterialessrc/ceramicas/7cbec-veneto-web_kge48a.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-20x62,color-marron", 15),
(94, "Caja ceramica bariloche beige (1,75 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348478/hcmaterialessrc/ceramicas/f26cc-bariloche-beige_jp1erz.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-beige", 15),
(95, "Caja ceramica bariloche gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348491/hcmaterialessrc/ceramicas/7098f-bariloche-gris_jhuecv.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-gris", 15),
(96, "Caja ceramica granito beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348509/hcmaterialessrc/ceramicas/Granito-Beige_eys6sq.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-beige", 15),
(97, "Caja ceramica granito gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348521/hcmaterialessrc/ceramicas/Granito-Gris_vvm1jh.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-gris", 15),
(98, "Caja ceramica niza beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348537/hcmaterialessrc/ceramicas/Niza-Beige-Marmol-Brillante_sjonlq.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-beige", 15),
(99, "Caja ceramica niza gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348550/hcmaterialessrc/ceramicas/Niza-Gris-Marmol-Brillante_ax9awy.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-gris", 15),
(100, "Caja ceramica malaga beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348566/hcmaterialessrc/ceramicas/Malaga-Beige_d4g40f.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-beige", 15),
(101, "Caja ceramica malaga gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348579/hcmaterialessrc/ceramicas/573a3-Malaga-Gris_mwxsc5.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-gris", 15),
(102, "Caja ceramica roca dolomita (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348600/hcmaterialessrc/ceramicas/Roca-Dolomita_gdfjwi.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-dolomita", 15),
(103, "Caja ceramica roca niquel (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348613/hcmaterialessrc/ceramicas/Roca-Niquel_hxaggg.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-niquel", 15),
(104, "Caja ceramica roca beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348624/hcmaterialessrc/ceramicas/Roca-Beige_hfmfxa.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-beige", 15),
(105, "Caja ceramica madera raiz (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348647/hcmaterialessrc/ceramicas/Madera-raiz_wnjrxx.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-raiz", 15),
(106, "Caja ceramica madera roble (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348830/hcmaterialessrc/ceramicas/Porto_x5fvwa.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-roble", 15),
(107, "Caja ceramica madera ebano (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348857/hcmaterialessrc/ceramicas/Madera-Ebano_worigx.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-ebano", 15),
(108, "Caja ceramica valencia beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348878/hcmaterialessrc/ceramicas/b4bed-Valencia-beige_yeqmeh.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-beige", 15),
(109, "Caja ceramica valencia gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348893/hcmaterialessrc/ceramicas/a694c-Valencia-gris_yig8yj.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-gris", 15),
(110, "Caja ceramica monaco tabaco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348924/hcmaterialessrc/ceramicas/Monaco-Tabaco-Geometrico_njlhoz.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-tabaco", 15),
(111, "Caja ceramica travertino natural (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668348955/hcmaterialessrc/ceramicas/TravertinoNatural_s1ovi2.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-37x37,color-natural", 15),
(112, "Caja ceramica madera calabria beige (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349002/hcmaterialessrc/ceramicas/49ae7-calabria-beige_nlwgrx.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-beige", 15),
(113, "Caja ceramica madera calabria natural (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349014/hcmaterialessrc/ceramicas/71303-calabria-nat_fcufo8.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-natural", 15),
(114, "Caja ceramica terme cemento (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349080/hcmaterialessrc/ceramicas/download_mxks2a.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-cemento", 15),
(115, "Caja ceramica florencia (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349143/hcmaterialessrc/ceramicas/9dd69-imagen-webinicial-sin-zoom_wcceke.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-toseto_calcareo", 15),
(116, "Caja ceramica sardegna beige (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349164/hcmaterialessrc/ceramicas/56c57-sarbeibge_bytj0z.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-beige", 15),
(117, "Caja ceramica sardegna gris (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349177/hcmaterialessrc/ceramicas/b384c-srdenga-gris_umlx21.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-gris", 15),
(118, "Caja ceramica padua beige (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349267/hcmaterialessrc/ceramicas/ae95a-padua-beige-cara-home-mini_xt6i2a.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-beige", 15),
(119, "Caja ceramica padua gris (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349291/hcmaterialessrc/ceramicas/a5f7b-padua-gris-cara-home-mini_otegot.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-gris", 15),
(120, "Caja ceramica toscana (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349356/hcmaterialessrc/ceramicas/720d1-toscana_ohjl79.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-toscana", 15),
(121, "Caja ceramica toscana gris (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349414/hcmaterialessrc/ceramicas/download_crvexr.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-gris", 15),
(122, "Caja ceramica roma (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349445/hcmaterialessrc/ceramicas/c3f6d-roma-inicial_c5n1vf.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-roma", 15),
(123, "Caja ceramica napoles beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349464/hcmaterialessrc/ceramicas/055ab-napoles-beige-cara-inicial_nxcu5s.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-beige", 15),
(124, "Caja ceramica napoles gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349500/hcmaterialessrc/ceramicas/ac31b-napoles-cara-inicial_ul9qkd.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-gris", 15),
(125, "Caja ceramica rimini beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349518/hcmaterialessrc/ceramicas/c20bf-rimini-b_dkxs6i.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-beige", 15),
(126, "Caja ceramica rimini gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349529/hcmaterialessrc/ceramicas/02321-rimini-gris_lgvois.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-gris", 15),
(127, "Caja ceramica rimini tiza (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349539/hcmaterialessrc/ceramicas/cf09b-rimmini-tiza_w3zdme.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-tiza", 15),
(128, "Caja ceramica botticino beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349574/hcmaterialessrc/ceramicas/bf450-BOTICCINO_NATURAL_nnzfrg.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-beige", 15),
(129, "Caja ceramica botticino gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349588/hcmaterialessrc/ceramicas/f3456-BOTICCINO_GRIS_fwv1sa.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-gris", 15),
(130, "Caja ceramica bologna beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349610/hcmaterialessrc/ceramicas/a1dbc-bbeige_z7s6m3.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-beige", 15),
(131, "Caja ceramica bologna gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349622/hcmaterialessrc/ceramicas/487d4-bologna-gris-prueba_edvejj.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-gris", 15),
(132, "Caja ceramica bologna arena (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349658/hcmaterialessrc/ceramicas/download_lfeeja.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-arena", 15),
(133, "Caja ceramica bologna tiza (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349635/hcmaterialessrc/ceramicas/e6710-bologna-tizza-producto_dhrqob.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-tiza", 15),
(134, "Caja ceramica varese beige (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349787/hcmaterialessrc/ceramicas/download_kutn4z.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-beige", 15),
(135, "Caja ceramica varese gris (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349714/hcmaterialessrc/ceramicas/85c6f-varese-gr1-web_frzn5z.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-gris", 15),
(136, "Caja ceramica varese tiza (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349728/hcmaterialessrc/ceramicas/4000b-varese_tiza2-web_zan5ve.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-tiza", 15),
(137, "Caja ceramica varese grafito (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349811/hcmaterialessrc/ceramicas/download_wzldyc.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-grafito", 15),
(138, "Caja ceramica treviso beige (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349897/hcmaterialessrc/ceramicas/download_tzopsf.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-beige", 15),
(139, "Caja ceramica treviso gris (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349916/hcmaterialessrc/ceramicas/download_agngti.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-gris", 15),
(140, "Caja ceramica carrara (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349938/hcmaterialessrc/ceramicas/d2f11-carrara-web_y1gwbd.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-carrara", 15),
(141, "Caja ceramica onix (1,9 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349953/hcmaterialessrc/ceramicas/a532e-onix-web_uhgrce.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-onix", 15),
(142, "Caja ceramica leon gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668349974/hcmaterialessrc/ceramicas/LeonGris_revestimiento_iijr4r.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(143, "Caja ceramica asturia beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350018/hcmaterialessrc/ceramicas/download_zzcr5r.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(144, "Caja ceramica asturia gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350035/hcmaterialessrc/ceramicas/download_he4glg.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(145, "Caja ceramica malaga beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350051/hcmaterialessrc/ceramicas/Malaga-Beige_lqq7vs.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(146, "Caja ceramica malaga gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350064/hcmaterialessrc/ceramicas/573a3-Malaga-Gris_oix58i.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(147, "Caja ceramica cartagena beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350105/hcmaterialessrc/ceramicas/053aa-cartagena-beige_rpxbtu.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(148, "Caja ceramica cartagena gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350377/hcmaterialessrc/ceramicas/download_imkez5.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(149, "Caja ceramica cartagena grafito (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350393/hcmaterialessrc/ceramicas/9821a-cartagena-grafito_gczcrq.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-grafito", 15),
(150, "Caja ceramica gerez beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350408/hcmaterialessrc/ceramicas/96594-tamano-beige_suwuxq.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(151, "Caja ceramica gerez gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350419/hcmaterialessrc/ceramicas/d26f9-gris-tamano_wahxu8.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(152, "Caja ceramica travertino natural (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350452/hcmaterialessrc/ceramicas/Trravertino-Natural_ges6hn.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-natural", 15),
(153, "Caja ceramica glaciar tramado (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350562/hcmaterialessrc/ceramicas/download_gocq85.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-tramado", 15),
(154, "Caja ceramica fraga beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350909/hcmaterialessrc/ceramicas/download_ahhrgz.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(155, "Caja ceramica fraga gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350927/hcmaterialessrc/ceramicas/download_eicuyn.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(156, "Caja ceramica fraga oxido (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350948/hcmaterialessrc/ceramicas/download_fmen3q.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-oxido", 15),
(157, "Caja ceramica sevilla beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350974/hcmaterialessrc/ceramicas/89dde-SEVILLA-BEIGE_dhxlre.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(158, "Caja ceramica sevilla gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668350985/hcmaterialessrc/ceramicas/ad8f8-SEVILLA-GRIS_hn4lvy.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(159, "Caja ceramica gijon (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351019/hcmaterialessrc/ceramicas/72342-GijonNuevo_izpupn.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-miero_venecita", 15),
(160, "Caja ceramica soria (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351051/hcmaterialessrc/ceramicas/6036a-SoriaNuevo_pppdnx.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-geometrico_lineal", 15),
(161, "Caja ceramica ibiza blanco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351079/hcmaterialessrc/ceramicas/bf50c-ibiza-blanco_hyxqbp.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-blanco", 15),
(162, "Caja ceramica ibiza azul (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351107/hcmaterialessrc/ceramicas/e2e43-ibiza-azul_owmp1q.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-azul", 15),
(163, "Caja ceramica calacatta brillante (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351176/hcmaterialessrc/ceramicas/937fb-calacata-web_jw1aie.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-brillante", 15),
(164, "Caja ceramica salamanca blanco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351233/hcmaterialessrc/ceramicas/download_aue03q.png", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-blanco", 15),
(165, "Caja ceramica salamanca beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351252/hcmaterialessrc/ceramicas/download_yqi1u6.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-beige", 15),
(166, "Caja ceramica salamanca gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351269/hcmaterialessrc/ceramicas/images_z8qip7.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-gris", 15),
(167, "Caja ceramica cadaques blanco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351290/hcmaterialessrc/ceramicas/003b3-cadaques_tyixrc.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-blanco", 15),
(168, "Caja ceramica fraga blanco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351341/hcmaterialessrc/ceramicas/download_in0soi.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-blanco", 15),
(169, "Caja ceramica bianco mate (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351364/hcmaterialessrc/ceramicas/8ad54-bianco-mate-original_bowrxt.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-blanco", 15),
(170, "Caja ceramica imola beige (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351412/hcmaterialessrc/ceramicas/download_xx4pum.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-beige", 15),
(171, "Caja ceramica imola gris (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351422/hcmaterialessrc/ceramicas/c7b72-imola-gris_rmoggd.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-gris", 15),
(172, "Caja ceramica imola tabaco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351433/hcmaterialessrc/ceramicas/2c3eb-imola-tabaco_be0dza.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-tabaco", 15),
(173, "Caja ceramica glaciar blanco (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351451/hcmaterialessrc/ceramicas/Glaciar-Blanco_d73gn7.gif", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-blanco", 15),
(174, "Caja ceramica glaciar negro brillante (2,2 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351466/hcmaterialessrc/ceramicas/c4142-glaciar-negro_lwa2go.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-43x43,color-negro_brillante", 15),
(175, "Caja ceramica calacatta mate (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351494/hcmaterialessrc/ceramicas/d7d0a-callacatta-b_t5xiwl.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-50x50,color-mate", 15),
(176, "Caja ceramica capena blanco (2,3 m2)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668351588/hcmaterialessrc/ceramicas/download_tkralm.jpg", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-61.5x61.5,color-blanco", 15),
(177, "Caja ceramica (2,3 m2)", "", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-x", 15),
(178, "Caja ceramica (2,3 m2)", "", 0, "Caja de ceramicas marca canuelas", 3, 1, "canuelas", "medida-32x47,color-x", 15),


INSERT INTO products VALUES
(179, "Mesada bacha integral (1,20x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668360915/hcmaterialessrc/cocina%20y%20ba%C3%B1o/F18gKaQMUdXDjPKXPuAS-medium_x6tswr.png", 0, "Mesada de Cocina de Mármol Sintético, con zócalo, bacha integral. La mesada y la bacha forman una sola pieza, sin juntas ni uniones. El fino borde antiderrame que se encuentra alrededor de la mesada impide que el agua derrame, ayudando a mantener un ambiente más limpio.", 2, 1, "durafort", "medida-1.20x0.60,color-gris_oscuro", 16),
(180, "Mesada bacha integral (1,20x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668361271/hcmaterialessrc/cocina%20y%20ba%C3%B1o/27q4aVJcx6M5xHCEpgSx-medium_xgzlfy.png", 0, "Mesada de Cocina de Mármol Sintético, sin zocalo, bacha integral. La mesada y la bacha forman una sola pieza, sin juntas ni uniones. El fino borde antiderrame que se encuentra alrededor de la mesada impide que el agua derrame, ayudando a mantener un ambiente más limpio.", 2, 1, "durafort", "medida-1.20x0.60,color-gris_oscuro", 16),
(181, "Mesada bacha integral (1,40x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668361437/hcmaterialessrc/cocina%20y%20ba%C3%B1o/e5yd3jV1ACzAJ5SsEuWM-medium_d6qmio.png", 0, "Mesada de Cocina de Mármol Sintético, con zócalo, bacha integral. La mesada y la bacha forman una sola pieza, sin juntas ni uniones. El fino borde antiderrame que se encuentra alrededor de la mesada impide que el agua derrame, ayudando a mantener un ambiente más limpio.", 2, 1, "durafort", "medida-1.40x0.60,color-gris", 16),
(182, "Mesada bacha integral (1,60x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668361524/hcmaterialessrc/cocina%20y%20ba%C3%B1o/5DA07gMBFQoZsdy0XImk-medium_wmqx0v.png", 0, "Mesada de Cocina de Mármol Sintético, con zócalo, bacha integral y bacha central. La mesada y la bacha forman una sola pieza, sin juntas ni uniones. El fino borde antiderrame que se encuentra alrededor de la mesada impide que el agua derrame, ayudando a mantener un ambiente más limpio.", 2, 1, "durafort", "medida-1.60x0.60,color-negro", 16),
(183, "Marmol sintetico con zócalo (1,20x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668361767/hcmaterialessrc/cocina%20y%20ba%C3%B1o/U5yRIV0Zx5tLktNYbmiS-medium_jtlx5x.png", 0, "Mesada de Cocina de Mármol Sintético, con zócalo, sin bacha", 2, 1, "durafort", "medida-1.20x0.60,color-negro", 16),
(184, "Marmol sintetico con zócalo (0,40x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668361935/hcmaterialessrc/cocina%20y%20ba%C3%B1o/gogg1ZzRgPoFS3BVXqVi-medium_ksrpry.png", 0, "Mesada de Cocina de Mármol Sintético, con zócalo, sin bacha", 2, 1, "durafort", "medida-0.40x0.60,color-gris_oscuro", 16),
(185, "Marmol sintetico sin zócalo (0,40x0,60)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668361964/hcmaterialessrc/cocina%20y%20ba%C3%B1o/Odzet616Onx6uaE43uEU-medium_sb8isy.png", 0, "Mesada de Cocina de Mármol Sintético, sin zócalo, sin bacha", 2, 1, "durafort", "medida-0.40x0.60,color-gris_oscuro", 16),
(186, "Pileta de lavadero para amurar (0,50x0,40x0,28)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668367647/hcmaterialessrc/cocina%20y%20ba%C3%B1o/wXOo25Cxf5VcvvXdk32V-medium_ng49kb.gif", 0, "Pileta para amurar. Las piletas de lavadero para amurar, permiten que estas se fijen en la pared, posibilitando un mayor espacio y comodidad a su alrededor. Incluye jabonera y fregadero", 2, 1, "durafort", "medida-0.50x0.40x0.28,color-blanco", 17),
(187, "Pileta de lavadero para amurar (0,60x0,50x0,30)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668367689/hcmaterialessrc/cocina%20y%20ba%C3%B1o/VKGjQ4602kpEnStIbnyj-medium_y34gvu.png", 0, "Pileta para amurar. Las piletas de lavadero para amurar, permiten que estas se fijen en la pared, posibilitando un mayor espacio y comodidad a su alrededor. Incluye jabonera y fregadero", 2, 1, "durafort", "medida-0.60x0.50x0.30,color-gris", 17),
(188, "Pileta de lavadero de apoyo (0,40x0,48x0,27)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668367734/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bCwvVoPh68dGGW9jzb8N-medium_rurdzw.png", 0, "Pileta de apoyo. Las piletas de lavadero para mueble o ménsulas, permiten el apoyo de estas en dichos sistemas, permitiendo hacer uso del mueble para mejor organización, siendo funcional y práctico. Incluye jabonera y fregadero", 2, 1, "durafort", "medida-0.40x0.48x0.27,color-blanco", 17),
(189, "Pileta de lavadero de apoyo (0,61x0,48x0,27)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668367749/hcmaterialessrc/cocina%20y%20ba%C3%B1o/c6fBTuTWTBoXAiQsRJ13-medium_tekceg.png", 0, "Pileta de apoyo. Las piletas de lavadero para mueble o ménsulas, permiten el apoyo de estas en dichos sistemas, permitiendo hacer uso del mueble para mejor organización, siendo funcional y práctico. Incluye jabonera y fregadero", 2, 1, "durafort", "medida-0.61x0.48x0.27,color-blanco", 17),
(190, "Pileta de lavadero de apoyo (0,80x0,48x0,27)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668367769/hcmaterialessrc/cocina%20y%20ba%C3%B1o/kjHOMRiuA7qZvleCIvIH-medium_rlqrwx.gif", 0, "Pileta de apoyo. Las piletas de lavadero para mueble o ménsulas, permiten el apoyo de estas en dichos sistemas, permitiendo hacer uso del mueble para mejor organización, siendo funcional y práctico. Incluye jabonera y fregadero", 2, 1, "durafort", "medida-0.80x0.48x0.27,color-blanco", 17),
(191, "Pileta doble de apoyo (1,00x0,52x0,25)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668367795/hcmaterialessrc/cocina%20y%20ba%C3%B1o/pNjq6n7lFiyDYjZCvFh6-medium_zt3odp.png", 0, "Pileta de apoyo. Las piletas de lavadero para mueble o ménsulas, permiten el apoyo de estas en dichos sistemas, permitiendo hacer uso del mueble para mejor organización, siendo funcional y práctico. Incluye jabonera y fregadero", 2, 1, "durafort", "medida-1.00x0.52x0.25,color-blanco", 17),
(192, "Mesada vanitory de marmol sintetico (0,50x0,40)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668368442/hcmaterialessrc/cocina%20y%20ba%C3%B1o/1gxCAHj6V57TB0aZteVE-medium_gclncc.png", 0, "Mesada de Vanitory para baño de Mármol Sintético", 2, 1, "durafort", "medida-0.50x0.40,color-blanco", 18),
(193, "Mueble 2 puertas con pie (0,50x0,40x0,80)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668368490/hcmaterialessrc/cocina%20y%20ba%C3%B1o/evKptjUktW5JEEId30xR-medium_wvpozh.png", 0, "", 2, 1, "durafort", "medida-0.50x0.40x0.80,color-blanco", 18),
(194, "Mueble 2 puertas para amurar (0,50x0,40x0,64)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668368507/hcmaterialessrc/cocina%20y%20ba%C3%B1o/p5Z7iVsZQLnD9JS24ef3-medium_lawk96.png", 0, "", 2, 1, "durafort", "medida-0.50x0.40x0.64,color-blanco", 18),
(195, "Alacena 3 puertas 1.20 blanca", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668369212/hcmaterialessrc/cocina%20y%20ba%C3%B1o/9D0iPEJ4Jcfxta9yPrUg-medium_gp7v1y.jpg", 0, "Alacenas en MDP. Muebles MS, excelente calidad y terminación para cocinas compactas, desarrollados para atender sus necesidades con mucha más practicidad.", 2, 1, "durafort", "ancho-120cm,alto-54cm,prof-30cm,color-blanco", 19),
(196, "Alacena 3 puertas 1.20 combinado", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668369225/hcmaterialessrc/cocina%20y%20ba%C3%B1o/MimRJDMxPHIvmywsTuIF-medium_crbdmx.jpg", 0, "Alacenas en MDP. Muebles MS, excelente calidad y terminación para cocinas compactas, desarrollados para atender sus necesidades con mucha más practicidad.", 2, 1, "durafort", "ancho-120cm,alto-54cm,prof-30cm,color-combinado", 19),
(197, "Alacena 3 puertas 1.40 blanca", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668369246/hcmaterialessrc/cocina%20y%20ba%C3%B1o/atRmQjsKmMP0bWdU8feX-medium_d5piku.jpg", 0, "Alacenas en MDP. Muebles MS, excelente calidad y terminación para cocinas compactas, desarrollados para atender sus necesidades con mucha más practicidad.", 2, 1, "durafort", "ancho-140cm,alto-54cm,prof-30cm,color-blanco", 19)

(198, "Columna lavatorio andina", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668383258/hcmaterialessrc/cocina%20y%20ba%C3%B1o/lavatorio-columna-andina-ferrum-bacha-blanco-and-cl-001-bl-b_2_q0ajht.jpg", 0, "Una línea eficiente y accesible pensada para el confort y el ahorro de agua. Cuenta con un lavatorio con pedestal para la zona de higiene de manos. Producto eficiente y funcional, inspirado en la sencillez de lo cotidiano.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 24)
(199, "Tapa asiento con sistema bidet universal", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668383963/hcmaterialessrc/cocina%20y%20ba%C3%B1o/tapas-asiento-bidet-tradicional-universal-ferrum-sanitarios-blanco-tra-tp-005-bl-b_1_mmx8eg.jpg", 0, "Las tapas asiento activas son una alternativa funcional para baños pequeños donde no se puede instalar un bidet convencional, y proveen al usuario de una alternativa cómoda para su uso diario.", 2, 1, "ferrum", "material-plastico(pp),color-blanco", 21)
(200, "Tapa asiento inodoro redondeada (uf)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668383979/hcmaterialessrc/cocina%20y%20ba%C3%B1o/tapas-asiento-inodoro-tradicional-andina-ferrum-sanitarios-blanco-and-tp-005-bl-b_4_1_xn1jw5.jpg", 0, "", 2, 1, "ferrum", "material-urea,color-blanco", 21)
(201, "Bidet andina (1 agujero)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668383996/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-andina-ferrum-sanitarios-blanco-and-bi-100-bl-b_2_niy6gz.jpg", 0, "Una línea eficiente y accesible pensada para el confort y el ahorro de agua. Cuenta con un lavatorio con pedestal para la zona de higiene de manos. Producto eficiente y funcional, inspirado en la sencillez de lo cotidiano.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(202, "Bidet andina (3 agujeros)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384009/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-andina-ferrum-sanitarios-blanco-and-bi-300-bl-b_2_v8vbmy.jpg", 0, "Una línea eficiente y accesible pensada para el confort y el ahorro de agua. Cuenta con un lavatorio con pedestal para la zona de higiene de manos. Producto eficiente y funcional, inspirado en la sencillez de lo cotidiano.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(203, "Bidet bari (3 agujeros)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384020/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-bari-ferrum-sanitarios-blanco-bar-bi-300-bl-b_5_eaicfo.jpg", 0, "La línea Bari presenta un formato versatil, que permite adaptarse en todo tipo de proyecto sin importar el tamaño del baño. Cuenta con un lavatorio con pedestal de generosas proporciones para la zona de higiene de manos.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(204, "Bidet bari (1 agujero)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384036/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-colgar-bari-de-colgar-ferrum-sanitarios-blanco-bar-bi-111-bl-b_1_j6lnea.jpg", 0, "Apta para espacios reducidos y ambientes que busquen expresar lo moderno desde el diseño. La línea Bari de colgar aporta en tu baño la sutileza de un espacio confortable Permite aumentar la sensación de amplitud en el baño y ofrece un diseño más liviano visualmente.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(205, "Bidet marina (3 agujeros)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384063/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-marina-ferrum-sanitarios-blanco-mar-bi-304-ne-b_v3sgwj.jpg", 0, "Marina es una línea de sanitarios versátil, alta y esbelta, para baños sofisticados. Se puede encontrar en color blanco o negro. Esta línea sanitaria se complementa con accesorios, lavatorios, vanitorys y bachas para personalizar tu baño al máximo. Producto de líneas suaves, dinámicas, inspiradas en la náutica", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(206, "Bidet marina (3 agujeros)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384077/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-marina-ferrum-sanitarios-blanco-mar-bi-304-bl-b_k5epoy.jpg", 0, "Marina es una línea de sanitarios versátil, alta y esbelta, para baños sofisticados. Se puede encontrar en color blanco o negro. Esta línea sanitaria se complementa con accesorios, lavatorios, vanitorys y bachas para personalizar tu baño al máximo. Producto de líneas suaves, dinámicas, inspiradas en la náutica", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(207, "Bidet marina (1 agujero)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384090/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-marina-ferrum-sanitarios-blanco-mar-bi-301-ne-b_qdyfvi.jpg", 0, "Marina es una línea de sanitarios versátil, alta y esbelta, para baños sofisticados. Se puede encontrar en color blanco o negro. Esta línea sanitaria se complementa con accesorios, lavatorios, vanitorys y bachas para personalizar tu baño al máximo. Producto de líneas suaves, dinámicas, inspiradas en la náutica", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 2)
(208, "Bidet marina (1 agujero)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384101/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-marina-ferrum-sanitarios-blanco-mar-bi-104-bl-b_xvsytu.jpg", 0, "Marina es una línea de sanitarios versátil, alta y esbelta, para baños sofisticados. Se puede encontrar en color blanco o negro. Esta línea sanitaria se complementa con accesorios, lavatorios, vanitorys y bachas para personalizar tu baño al máximo. Producto de líneas suaves, dinámicas, inspiradas en la náutica", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(209, "Tapa bidet bari (hdf)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384113/hcmaterialessrc/cocina%20y%20ba%C3%B1o/tapas-asiento-bidet-tradicional-bari-ferrum-sanitarios-blanco-bar-tp-003-bl-b_2_lu6t83.jpg", 0, "La tapa para bidet es un producto innovador para contribuir en el orden y la comodidad dentro del cuarto de baño. Está disponible solo para algunas líneas sanitarias, tanto para los bidet con grifería monocomando como para los de grifería tradicional.", 2, 1, "ferrum", "material-madera(hdf),color-blanco", 21)
(210, "Tapa asiento inodoro bari (hdf)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384128/hcmaterialessrc/cocina%20y%20ba%C3%B1o/tapas-asiento-inodoro-tradicional-bari-ferrum-sanitarios-blanco-bar-tp-011-bl-b_2_bnadk4.jpg", 0, "", 2, 1, "ferrum", "material-madera(hdf),color-blanco", 21)
(211, "Bidet bari (1 agujero)", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384140/hcmaterialessrc/cocina%20y%20ba%C3%B1o/bidet-de-pie-bari-ferrum-sanitarios-blanco-bar-bi-100-bl-b_3_r8px6g.jpg", 0, "La línea Bari presenta un formato versatil, que permite adaptarse en todo tipo de proyecto sin importar el tamaño del baño. Cuenta con un lavatorio con pedestal de generosas proporciones para la zona de higiene de manos.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 22)
(212, "Inodoro largo andina", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384176/hcmaterialessrc/cocina%20y%20ba%C3%B1o/inodoro-de-pie-largo-andina-ferrum-sanitarios-blanco-and-in-002-bl-b_2_qbikhe.jpg", 0, "Una línea eficiente y accesible pensada para el confort y el ahorro de agua. Cuenta con un lavatorio con pedestal para la zona de higiene de manos. Producto eficiente y funcional, inspirado en la sencillez de lo cotidiano.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 20)
(213, "Deposito de colgar andina 9 litros", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384192/hcmaterialessrc/cocina%20y%20ba%C3%B1o/deposito-de-colgar-andina-ferrum-sanitarios-blanco-and-dp-010-bl-b_2_czkxsu.jpg", 0, "Una línea eficiente y accesible pensada para el confort y el ahorro de agua. Cuenta con un lavatorio con pedestal para la zona de higiene de manos. Producto eficiente y funcional, inspirado en la sencillez de lo cotidiano.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 23)
(214, "Deposito apoyar simple descarga andina 4,5 litros", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384207/hcmaterialessrc/cocina%20y%20ba%C3%B1o/deposito_inodorolargoandina_grande_nhof40.jpg", 0, "Una línea eficiente y accesible pensada para el confort y el ahorro de agua. Cuenta con un lavatorio con pedestal para la zona de higiene de manos. Producto eficiente y funcional, inspirado en la sencillez de lo cotidiano.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 23)
(215, "Deposito doble descarga bari", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668384220/hcmaterialessrc/cocina%20y%20ba%C3%B1o/deposito-apoyar-bari-ferrum-sanitarios-blanco-bar-dp-006-bl-b_1_bjwfyu.jpg", 0, "La línea Bari presenta un formato versatil, que permite adaptarse en todo tipo de proyecto sin importar el tamaño del baño. Cuenta con un lavatorio con pedestal de generosas proporciones para la zona de higiene de manos.", 2, 1, "ferrum", "material-porcelana_sanitaria,color-blanco", 23)
(216, "", "", 0, "", 2, 1, "ferrum", "material-,color-blanco", 19)
(216, "Puerta doble chapa inyectada mod 5530", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668962867/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/5530-PEURTA_cayh1q.jpg", 0, "Puerta de alta gama con postigo de abrir lateral, marco americano 12 cm, 4 bisagras embutidas, Cerradura y cerrojo con la misma combinación, Barral rectangular de 100 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(217, "Puerta doble chapa inyectada mod 1500T", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668962897/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500tPUERTA_tzszjp.jpg", 0, "Puerta de alta gama con Ciega moldurada con apliques de aluminio, Marco americano de 12 cm, 4 bisagas embutidas, Cerradura y cerrojo con la misma combinación, Barral de 60 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(218, "Portón doble chapa inyectada mod 1500T", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668962943/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500tPORTON_oazivs.jpg", 0, "Porton de alta gama con Ciega moldurada con apliques de aluminio, Marco americano de 12 cm, 4 bisagas embutidas, Barral de 60 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 26)
(219, "Puerta doble chapa inyectada con una portada", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668962957/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500tPUERTA-CON-PORTADA-1_enzdmk.jpg", 0, "Puerta de alta gama con una portada, Ciega moldurada con apliques de aluminio, Doble chapa inyectada, Marco americano de 12 cm, 4 bisagas embutidas, Cerradura y cerrojo con la misma combinación, Barral de 60 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(220, "Puerta doble chapa inyectada con dos portadas", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668962976/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500tPUERTA-CON-2-PORTADAS-1_sjn1u4.jpg", 0, "Puerta de alta gama con dos portadas, Ciega moldurada con apliques de aluminio, Doble chapa inyectada, Marco americano de 12 cm, 4 bisagas embutidas, Cerradura y cerrojo con la misma combinación, Barral de 60 cm ", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(221, "Puerta doble chapa inyectada mod 1500", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668962994/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500PUERTA_xbe5xq.jpg", 0, "Puerta de media gama, Doble chapa inyectada, Marco americano de 12 cm, 4 bisagas embutidas, Barral de acero inoxidable 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(222, "Puerta doble chapa inyectada mod 1500", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963010/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500PUERTA-T_xbpugh.jpg", 0, "Puerta de media gama, Ciega moldurada, Doble chapa inyecatda c/barral, SOLO NEGRA c/ apliques de aluminio, Marco americano de 12 cm, 4 bisagras embutidas, Barral de acero inoxidable de 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(223, "Puerta doble chapa inyectada con una portada", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963023/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500-PUERTA-CON-PORTADA_aatsis.jpg", 0, "Puerta de media gama con una portada, Ciega moldurada, Doble chapa inyecatda c/barral, SOLO NEGRA c/ apliques de aluminio, Marco americano de 12 cm, 4 bisagras embutidas, Barral de acero inoxidable de 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(224, "Puerta doble chapa inyectada con dos portadas", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963037/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1500-PUERTA-CON-2-PORTADAS_eenzwa.jpg", 0, "Puerta de media gama con dos portadas, Ciega moldurada, Doble chapa inyecatda c/barral, SOLO NEGRA c/ apliques de aluminio, Marco americano de 12 cm, 4 bisagras embutidas, Barral de acero inoxidable de 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(225, "Puerta doble chapa inyectada mod 1530", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963049/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1530PUERTA_lwjxg9.jpg", 0, "Puerta de media gama, Doble chapa inyectada, Marco americano 12 cm,4 bisagras embutidas, Barral de 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(226, "Portón doble chapa inyectada mod 1530", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963063/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/1530PORTON_pbkk9u.jpg", 0, "Portón de gama media con Doble chapa inyectada, Marco americano 12 cm, 4 bisagras embutidas, Barral de 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 26)
(227, "Puerta doble chapa inyectada mod 5000", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963074/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/5000PUERTA_ax6wpv.jpg", 0, "Puerta doble chapa inyectada de gama media, Ciega lisa doble chapa inyectada, Marco americano de 12 cm, 3 bisagras embutidas con manijón de aluminio", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(228, "Puerta doble chapa inyectada mod 5000 CB", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963094/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/5000CB-PUERTA_prh8px.jpg", 0, "Puerta doble chapa inyectada de gama media, Ciega lisa doble chapa inyectada, Marco americano de 12 cm, 3 bisagras embutidas, Manijón de acero inoxidable de 40 cm", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(229, "Puerta doble chapa inyectada mod 4100", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963106/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/4100PUERTA_mejstg.jpg", 0, "Puerta doble chapa inyectada de gama media, Ciega estampada americana doble chapa Inyectada, Marco americano de 12 cm, 3 bisagras embutidas con manijón de aluminio", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(230, "Puerta doble chapa inyectada mod 4110", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963121/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/4110PUERTA_ozkl6s.jpg", 0, "Puerta doble chapa inyectada de gama media, 1/2 reja con postigo de abrir, Estampada Americana, Doble chapa Inyectada, Marco americano de 12 cm, 3 bisagras embutidas", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(231, "Portón doble chapa inyectada mod 4110", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963138/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/4110PORTON_v9onpb.jpg", 0, "Portón de gama media con Doble chapa inyectada, 1/2 reja con postigo de abrir, Estampada Americana, Marco americano de 12 cm, 3 bisagras embutidas", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 26)
(232, "Puerta doble chapa inyectada mod 4130", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963149/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/4130PUERTA_qwlsil.jpg", 0, "Puerta doble chapa inyectada de gama media, Reja lateral con postigo de abrir, Estampada americana, Marco americano de 12 cm, 3 bisagras embutidas, Manijón de aluminio", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(233, "Portón doble chapa inyectada mod 4130", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963162/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/4130PORTON_socrqo.jpg", 0, "Portón de gama media con Doble chapa inyectada, Reja lateral con postigo de abrir, Estampada americana, Marco americano de 12 cm, 3 bisagras embutidas, Manijón de aluminio", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 26)
(234, "Puerta doble chapa inyectada mod 2530", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963174/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/2530PUERTA-1_vhcbos.jpg", 0, "Puerta doble chapa inyectada de gama alta, Postigo de abrir central, Marco americano 12 cm, 4 bisagras embutidas, Cerradura y cerrojo con la misma combinacion, barral rectangular de 60 cm", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(235, "Puerta doble chapa inyectada mod 2500", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963186/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/2500PUERTA-1_gqag2i.jpg", 0, "Puerta doble chapa inyectada de gama alta con Moldurada, Marco americano 12 cm, 4 bisagras embutidas, Cerradura y cerrojo con la misma combinación, Barral rectangular de 60 cm", 3, 1, "atex", "material-chapa_inyectada,color-blanco", 25)
(236, "Puerta doble chapa inyectada mod 5500 E", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963197/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/5500E-PUERTA_oltgwa.jpg", 0, "Puerta doble chapa inyectada de gama alta, Estampada con apliques de aluminio, Marco americano 12 cm, 4 bisagras embutidas, Cerradura y cerrojo con la misma combinación, Barral rectangular de 100 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(237, "Puerta doble chapa inyectada con una portada", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963217/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/5500E-PUERTA1PORTADA-1_blvemd.jpg", 0, "Puerta de gama alta con una portada, Estampada con apliques de aluminio, Doble chapa inyectada, Marco americano 12 cm, 4 bisagras embutidas, Cerradura y cerrojo con la misma combinación, Barral rectangular de 100 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)
(238, "Puerta doble chapa inyectada con dos portadas", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668963232/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/5500E-PUERTA2PORTADA_orp1ek.jpg", 0, "Puerta de gama alta con dos portada, Estampada con apliques de aluminio, Doble chapa inyectada, Marco americano 12 cm, 4 bisagras embutidas, Cerradura y cerrojo con la misma combinación, Barral rectangular de 100 cm", 3, 1, "atex", "material-chapa_inyectada,color-negro", 25)

BREMEN

(239, "Cuchara de Albañil Forjada Punta Standard", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668984856/hcmaterialessrc/maquinarias%20y%20herramientas/con-7226-bremen-cucharas-de-albanil-forjadas_2_ppwfea.jpg", 0, "Fabricadas íntegramente en acero forjado, proceso que otorga una mayor dureza superficial y mejora sustancialmente la resistencia al desgaste. Cuentan con empuñadura en ángulo de 25° respecto de la hoja, lo que permite trabajar de forma ergonómica, con una mejor postura de la muñeca. Virolas fabricadas en acero cincado.", 4, 1, "bremen", "material-acero_carbono,medida-7_pulgadas", 28)
(241, "Cuchara de Albañil Forjada Punta Roma", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668984856/hcmaterialessrc/maquinarias%20y%20herramientas/con-7226-bremen-cucharas-de-albanil-forjadas_2_ppwfea.jpg", 0, "Fabricadas íntegramente en acero forjado, proceso que otorga una mayor dureza superficial y mejora sustancialmente la resistencia al desgaste. Cuentan con empuñadura en ángulo de 25° respecto de la hoja, lo que permite trabajar de forma ergonómica, con una mejor postura de la muñeca. Virolas fabricadas en acero cincado.", 4, 1, "bremen", "material-acero_carbono,medida-7_pulgadas", 28)
(242, "Cuchara de Albañil Forjada Punta Standard", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668984856/hcmaterialessrc/maquinarias%20y%20herramientas/con-7226-bremen-cucharas-de-albanil-forjadas_2_ppwfea.jpg", 0, "Fabricadas íntegramente en acero forjado, proceso que otorga una mayor dureza superficial y mejora sustancialmente la resistencia al desgaste. Cuentan con empuñadura en ángulo de 25° respecto de la hoja, lo que permite trabajar de forma ergonómica, con una mejor postura de la muñeca. Virolas fabricadas en acero cincado.", 4, 1, "bremen", "material-acero_carbono,medida-8_pulgadas", 28)
(243, "Cuchara de Albañil Forjada Punta Roma", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668984856/hcmaterialessrc/maquinarias%20y%20herramientas/con-7226-bremen-cucharas-de-albanil-forjadas_2_ppwfea.jpg", 0, "Fabricadas íntegramente en acero forjado, proceso que otorga una mayor dureza superficial y mejora sustancialmente la resistencia al desgaste. Cuentan con empuñadura en ángulo de 25° respecto de la hoja, lo que permite trabajar de forma ergonómica, con una mejor postura de la muñeca. Virolas fabricadas en acero cincado.", 4, 1, "bremen", "material-acero_carbono,medida-8_pulgadas", 28)
(244, "Cuchara de Albañil Soldada Cucharin", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995683/hcmaterialessrc/maquinarias%20y%20herramientas/con-7221-bremen-cuchara-albanil-soldada-5-12_1_ljzkfx.jpg", 0, "El mango y la lámina están unidos a través de una soldadura. El mango y su altura fueron especialmente desarrollados para tener un mejor agarre y un uso más confortable de la herramienta. También cuenta con un tapón de acero en su extremo superior.", 4, 1, "bremen", "material-acero_carbono,medida-5_1/2_pulgadas", 28)
(245, "Cuchara de Albañil Soldada Punta Standar", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995704/hcmaterialessrc/maquinarias%20y%20herramientas/con-7223-bremen-cuchara-albanil-soldada-standar_1_eez5ti.jpg", 0, "El mango y la lámina están unidos a través de una soldadura. El mango y su altura fueron especialmente desarrollados para tener un mejor agarre y un uso más confortable de la herramienta. También cuenta con un tapón de acero en su extremo superior.", 4, 1, "bremen", "material-acero_carbono,medida-7_pulgadas", 28)
(246, "Cuchara de Albañil Soldada Punta Roma", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995724/hcmaterialessrc/maquinarias%20y%20herramientas/con-7222-bremen-cuchara-albanil-soldada-roma_1_bhesy4.jpg", 0, "El mango y la lámina están unidos a través de una soldadura. El mango y su altura fueron especialmente desarrollados para tener un mejor agarre y un uso más confortable de la herramienta. También cuenta con un tapón de acero en su extremo superior.", 4, 1, "bremen", "material-acero_carbono,medida-7_pulgadas", 28)
(247, "Cuchara de Albañil Soldada Punta Standar", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995704/hcmaterialessrc/maquinarias%20y%20herramientas/con-7223-bremen-cuchara-albanil-soldada-standar_1_eez5ti.jpg", 0, "El mango y la lámina están unidos a través de una soldadura. El mango y su altura fueron especialmente desarrollados para tener un mejor agarre y un uso más confortable de la herramienta. También cuenta con un tapón de acero en su extremo superior.", 4, 1, "bremen", "material-acero_carbono,medida-8_pulgadas", 28)
(248, "Cuchara de Albañil Soldada Punta Roma", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995724/hcmaterialessrc/maquinarias%20y%20herramientas/con-7222-bremen-cuchara-albanil-soldada-roma_1_bhesy4.jpg", 0, "El mango y la lámina están unidos a través de una soldadura. El mango y su altura fueron especialmente desarrollados para tener un mejor agarre y un uso más confortable de la herramienta. También cuenta con un tapón de acero en su extremo superior.", 4, 1, "bremen", "material-acero_carbono,medida-8_pulgadas", 28)
(249, "Arco Sierra Tubular", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995746/hcmaterialessrc/maquinarias%20y%20herramientas/var-7034-bremen-arco-de-sierra-tubular_1_sfogyv.jpg", 0, "Medida Hoja: 12 pulgadas - Material Hoja: Acero #60 - Material Mango: TPR - Material Marco: Acero A3 + Aluminio", 3, 1, "bremen", "material-acero_y_aluminio,peso-0.361,medida-12_pulgadas", 29)
(250, "Espátula Tapizadora para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995772/hcmaterialessrc/maquinarias%20y%20herramientas/con-7246-bremen-dw-espatula-tapizadora_1_lnupql.jpg", 0, "Tope metálico. Material mango: PP & TPR", 3, 1, "bremen", "material-acero_inoxidable,peso-x,medida-10_pulgadas", 28)
(251, "Espátula Tapizadora para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995772/hcmaterialessrc/maquinarias%20y%20herramientas/con-7246-bremen-dw-espatula-tapizadora_1_lnupql.jpg", 0, "Tope metálico. Material mango: PP & TPR", 3, 1, "bremen", "material-acero_inoxidable,peso-x,medida-12_pulgadas", 28)
(252, "Espátula Esquinera Externa para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995803/hcmaterialessrc/maquinarias%20y%20herramientas/con-7248-bremen-dw-espatula-esquinera-externa_1_cmpi8j.jpg", 0, "Material mango: PP & TPR, Espátula para esparcir la masilla en ángulos externos de las placas de construcción en seco.", 3, 1, "bremen", "material-acero_inoxidable", 28)
(253, "Espátula Esquinera Interna para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995816/hcmaterialessrc/maquinarias%20y%20herramientas/con-7249-bremen-dw-espatula-esquinera-interna_1_ud9t03.jpg", 0, "Material mango: PP & TPR, Espátula para esparcir la masilla en la unión interna de las placas de construcción en seco.", 3, 1, "bremen", "material-acero_inoxidable", 28)
(254, "Espátula Flexible para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995850/hcmaterialessrc/maquinarias%20y%20herramientas/con-7251-bremen-dw-espatula-flexible_1_fhewn6.jpg", 0, "Tope metálico. Material mango: PP & TPR", 3, 1, "bremen", "material-acero_inoxidable,largo-152mm,medida-6_pulgadas", 28)
(255, "Espátula Flexible para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995850/hcmaterialessrc/maquinarias%20y%20herramientas/con-7251-bremen-dw-espatula-flexible_1_fhewn6.jpg", 0, "Tope metálico. Material mango: PP & TPR", 3, 1, "bremen", "material-acero_inoxidable,largo-127mm,medida-5_pulgadas", 28)
(256, "Espátula Flexible para Construcción en Seco", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995850/hcmaterialessrc/maquinarias%20y%20herramientas/con-7251-bremen-dw-espatula-flexible_1_fhewn6.jpg", 0, "Tope metálico. Material mango: PP & TPR", 3, 1, "bremen", "material-acero_inoxidable,largo-101mm,medida-4_pulgadas", 28)
(257, "Disco Diamantado Turbo Fino", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995873/hcmaterialessrc/maquinarias%20y%20herramientas/con-4525-bremen-disco-diamantado-bremen_7_xvu7li.jpg", 0, "Para Azulejos, Cerámicas de Mono y Doble Cocción, Mármoles, Porcelanas, Porcelanatos Silestone y Placas de Yeso", 3, 1, "bremen", "peso-0.145,medida-4½_pulgadas", 30)
(258, "Disco Diamantado Turbo Fino", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1668995873/hcmaterialessrc/maquinarias%20y%20herramientas/con-4525-bremen-disco-diamantado-bremen_7_xvu7li.jpg", 0, "Para Azulejos, Cerámicas de Mono y Doble Cocción, Mármoles, Porcelanas, Porcelanatos Silestone y Placas de Yeso", 3, 1, "bremen", "peso-0.34,medida-7_pulgadas", 30)
(259, "Disco Flap - Óxido de Aluminio", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074681/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7209-bremen-disco-flap-oxido-de-aluminio_1_j95t0c.jpg", 0, "Los Discos Flap BREMEN tienen una forma convexa, usualmente llamada de centro deprimido, que permite una mayor superficie de contacto entre el disco y la superficie a desbastar o lijar.", 3, 1, "bremen", "material-oxido_de_aluminio,medida-4½_pulgadas_115mm,grano-80", 30)
(260, "Disco Flap - Óxido de Aluminio", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074681/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7209-bremen-disco-flap-oxido-de-aluminio_1_j95t0c.jpg", 0, "Los Discos Flap BREMEN tienen una forma convexa, usualmente llamada de centro deprimido, que permite una mayor superficie de contacto entre el disco y la superficie a desbastar o lijar.", 3, 1, "bremen", "material-oxido_de_aluminio,medida-4½_pulgadas_115mm,grano-120", 30)
(261, "Cinta Métrica Autofrenante 5m", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074704/hcmaterialessrc/maquinarias%20y%20herramientas/con-7612-bremen-cinta-metrica-heavy-duty_3_dtconp.jpg", 0, "Cuerpo de ABS recubierto con TPR, material ergonómico y antideslizante, Su hoja se mantiene extendida a la longitud deseada sin necesidad de presionar ningún botón, gracias a un mecanismo interno de bloqueo automático que impide que se retraiga. El botón únicamente debe presionarse para retraerla.", 3, 1, "bremen", "material-ABS_y_TPR,largo-5m", 31)
(262, "Cinta Métrica Autofrenante 8m", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074704/hcmaterialessrc/maquinarias%20y%20herramientas/con-7612-bremen-cinta-metrica-heavy-duty_3_dtconp.jpg", 0, "Cuerpo de ABS recubierto con TPR, material ergonómico y antideslizante, Su hoja se mantiene extendida a la longitud deseada sin necesidad de presionar ningún botón, gracias a un mecanismo interno de bloqueo automático que impide que se retraiga. El botón únicamente debe presionarse para retraerla.", 3, 1, "bremen", "material-ABS_y_TPR,largo-8m", 31)
(263, "Candado de Bronce Doble Traba a Bolilla 30mm", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074725/hcmaterialessrc/maquinarias%20y%20herramientas/var-7126-bremen-candado-doble-entrada-a-bolilla_1_gghtcr.jpg", 0, "Candado con cuerpo de bronce macizo. Incluye 3 llaves de bronce. Aro cementado para mayor resistencia. Doble traba a bolilla de acero inoxidable para seguridad superior. Reten de goma que evita el contacto con el agua.", 3, 1, "bremen", "material-bronce,medida-30mm", 32)
(264, "Candado de Bronce Doble Traba a Bolilla 40mm", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074725/hcmaterialessrc/maquinarias%20y%20herramientas/var-7126-bremen-candado-doble-entrada-a-bolilla_1_gghtcr.jpg", 0, "Candado con cuerpo de bronce macizo. Incluye 3 llaves de bronce. Aro cementado para mayor resistencia. Doble traba a bolilla de acero inoxidable para seguridad superior. Reten de goma que evita el contacto con el agua.", 3, 1, "bremen", "material-bronce,medida-40mm", 32)
(265, "Candado de Bronce Doble Traba a Bolilla 50mm", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074725/hcmaterialessrc/maquinarias%20y%20herramientas/var-7126-bremen-candado-doble-entrada-a-bolilla_1_gghtcr.jpg", 0, "Candado con cuerpo de bronce macizo. Incluye 3 llaves de bronce. Aro cementado para mayor resistencia. Doble traba a bolilla de acero inoxidable para seguridad superior. Reten de goma que evita el contacto con el agua.", 3, 1, "bremen", "material-bronce,medida-50mm", 32)
(266, "Disco Flap - Óxido de Aluminio grano 40", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074745/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7209-bremen-disco-flap-oxido-de-aluminio_1_hy3xvs.jpg", 0, "Los Discos Flap BREMEN tienen una forma convexa, usualmente llamada de centro deprimido, que permite una mayor superficie de contacto entre el disco y la superficie a desbastar o lijar. Base plástica. Buje 7/8 pulgadas (22mm)", 3, 1, "bremen", "material-oxido_de_aluminio,medida-4½_pulgadas_115mm,grano-40", 30)
(267, "Disco Flap - Óxido de Aluminio grano 60", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074745/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7209-bremen-disco-flap-oxido-de-aluminio_1_hy3xvs.jpg", 0, "Los Discos Flap BREMEN tienen una forma convexa, usualmente llamada de centro deprimido, que permite una mayor superficie de contacto entre el disco y la superficie a desbastar o lijar. Base plástica. Buje 7/8 pulgadas (22mm)", 3, 1, "bremen", "material-oxido_de_aluminio,medida-4½_pulgadas_115mm,grano-60", 30)
(268, "Lija al Agua", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074762/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7563-bremen-lija-al-agua_1_sofoek.jpg", 0, "Disponibles en grano 100, 120, 150, 180, 220, 1200, 1500 y 2000.El Envase es un Estuche de Cartón Termosellado para evitar el ingreso de humedad", 3, 1, "bremen", "material-carburo_de_silicio,peso-x,medida-230x280mm", 33)
(269, "Lija Anti-Empaste", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074780/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7581-bremen-lija-anti-empaste_1_rlaz2q.jpg", 0, "Disponible en grano 80, 100, 120, 150. El Envase es un Estuche de Cartón Termosellado para evitar el ingreso de humedad", 3, 1, "bremen", "material-oxido_de_aluminio,medida-230x280mm", 33)
(270, "Lija para madera", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669074797/hcmaterialessrc/maquinarias%20y%20herramientas/ins-7589-bremen-lija-para-madera_1_cwet9d.jpg", 0, "Disponible en grano 60, 80, 100, 120, 150, 220. El Envase es un Estuche de Cartón Termosellado para evitar el ingreso de humedad", 3, 1, "bremen", "material-oxido_de_aluminio,color-marron,medida-230x280mm", 33)

HERFASA

(271, "Puerta hoja de pino m/aluminio derecha 0,70", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589638/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-aluminio-1_fgrx6k.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.70x200cm,prof-7cm,marco-aluminio,apertura-derecha", 27)
(272, "Puerta hoja de pino m/aluminio izquierda 0,70", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589638/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-aluminio-1_fgrx6k.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.70x200cm,prof-7cm,marco-aluminio,apertura-izquierda", 27)
(273, "Puerta hoja de pino m/aluminio derecha 0,80", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589638/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-aluminio-1_fgrx6k.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.80x200cm,prof-7cm,marco-aluminio,apertura-derecha", 27)
(274, "Puerta hoja de pino m/aluminio izquierda 0,80", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589638/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-aluminio-1_fgrx6k.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.80x200cm,prof-7cm,marco-aluminio,apertura-izquierda", 27)
(275, "Puerta hoja de pino m/pino izquierda 0,70", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589723/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-madera-1-1_sx8gvw.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.70x200cm,prof-7cm,marco-pino,apertura-izquierda", 27)
(276, "Puerta hoja de pino m/pino derecha 0,70", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589723/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-madera-1-1_sx8gvw.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.70x200cm,prof-7cm,marco-pino,apertura-derecha", 27)
(277, "Puerta hoja de pino m/pino izquierda 0,80", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589723/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-madera-1-1_sx8gvw.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.80x200cm,prof-7cm,marco-pino,apertura-izquierda", 27)
(278, "Puerta hoja de pino m/pino derecha 0,80", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589723/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-marco-madera-1-1_sx8gvw.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-pino,medida-0.80x200cm,prof-7cm,marco-pino,apertura-derecha", 27)
(279, "Puerta hoja de cedrillo m/aluminio derecha 0,70", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589753/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-cedrillo1_u6tegf.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-cedrillo,medida-0.70x200cm,prof-7cm,marco-aluminio,apertura-derecha", 27)
(280, "Puerta hoja de cedrillo m/aluminio izquierda 0,70", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589753/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-cedrillo1_u6tegf.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-cedrillo,medida-0.70x200cm,prof-7cm,marco-aluminio,apertura-izquierda", 27)
(281, "Puerta hoja de cedrillo m/aluminio derecha 0,80", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589753/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-cedrillo1_u6tegf.jpg", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "herfasa", "material-cedrillo,medida-0.80x200cm,prof-7cm,marco-aluminio,apertura-derecha", 27)
(282, "Puerta hoja de cedrillo m/aluminio izquierda 0,80", "https://res.cloudinary.com/dqdmm93bn/image/upload/v1669589753/hcmaterialessrc/pisos%2C%20pinturas%20y%20terminaciones/placa-cedrillo1_u6tegf.jp27", 0, "Puerta de interior con Cerradura interna + juego de llaves, Esquineros individuales de cartón + film protector.", 3, 1, "bremen", "material-cedrillo,medida-0.80x200cm,prof-7cm,marco-aluminio,apertura-izquierda", 27)


(283, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(284, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(285, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(286, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(287, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(288, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(289, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(290, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(291, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(292, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(293, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(294, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(295, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(296, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(297, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(298, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(299, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)
(300, "", "", 0, "", 3, 1, "bremen", "material-,peso-x,medida-x", 19)



